// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_bluetooth_mode = "CgkIu5mLkuoXEAIQBA"; // <GPGSID>
        public const string achievement_10_wins_against_the_ai = "CgkIu5mLkuoXEAIQCg"; // <GPGSID>
        public const string achievement_play_50_games = "CgkIu5mLkuoXEAIQHQ"; // <GPGSID>
        public const string achievement_50_wins_against_the_ai = "CgkIu5mLkuoXEAIQCw"; // <GPGSID>
        public const string achievement_level_30 = "CgkIu5mLkuoXEAIQEQ"; // <GPGSID>
        public const string achievement_google_play_multiplayer_mode = "CgkIu5mLkuoXEAIQBQ"; // <GPGSID>
        public const string achievement_play_100_games = "CgkIu5mLkuoXEAIQHg"; // <GPGSID>
        public const string achievement_play_10000_games = "CgkIu5mLkuoXEAIQIg"; // <GPGSID>
        public const string achievement_100_wins_against_the_ai = "CgkIu5mLkuoXEAIQDQ"; // <GPGSID>
        public const string achievement_win_50_times_against_hard_ai = "CgkIu5mLkuoXEAIQFg"; // <GPGSID>
        public const string achievement_is_it_only_an_eggplant_wink_wink = "CgkIu5mLkuoXEAIQGg"; // <GPGSID>
        public const string achievement_50_games_against_ai = "CgkIu5mLkuoXEAIQBw"; // <GPGSID>
        public const string achievement_rekt = "CgkIu5mLkuoXEAIQGw"; // <GPGSID>
        public const string achievement_1000_games_against_the_ai = "CgkIu5mLkuoXEAIQCQ"; // <GPGSID>
        public const string achievement_noobnoobnoobnoobnoobnoobnoob = "CgkIu5mLkuoXEAIQHA"; // <GPGSID>
        public const string achievement_play_500_games = "CgkIu5mLkuoXEAIQHw"; // <GPGSID>
        public const string achievement_1000_wins_against_the_ai = "CgkIu5mLkuoXEAIQDg"; // <GPGSID>
        public const string achievement_win_1000_times_against_the_hard_ai = "CgkIu5mLkuoXEAIQGA"; // <GPGSID>
        public const string achievement_100_games_against_ai = "CgkIu5mLkuoXEAIQCA"; // <GPGSID>
        public const string achievement_first_win = "CgkIu5mLkuoXEAIQAg"; // <GPGSID>
        public const string achievement_win_250_times_against_the_hard_ai = "CgkIu5mLkuoXEAIQFw"; // <GPGSID>
        public const string achievement_play_5000_games = "CgkIu5mLkuoXEAIQIQ"; // <GPGSID>
        public const string achievement_level_15 = "CgkIu5mLkuoXEAIQEA"; // <GPGSID>
        public const string achievement_250_wins_against_the_ai = "CgkIu5mLkuoXEAIQDA"; // <GPGSID>
        public const string achievement_fabulous = "CgkIu5mLkuoXEAIQFQ"; // <GPGSID>
        public const string achievement_level_5 = "CgkIu5mLkuoXEAIQDw"; // <GPGSID>
        public const string achievement_local_multiplayer_mode = "CgkIu5mLkuoXEAIQAw"; // <GPGSID>
        public const string achievement_10_games_against_ai = "CgkIu5mLkuoXEAIQBg"; // <GPGSID>
        public const string achievement_play_1000_games = "CgkIu5mLkuoXEAIQIA"; // <GPGSID>

}

